import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'hello world',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
      className='dark' //手动切换系统颜色 dark
      >{children}</body>
    </html>
  )
}
