import AppContextProvider from "@/components/AppCpntext";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "hello world",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
